spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ming

server:
  port: 8094

keycloak:
  auth-server-url: http://localhost:8080/auth

realm:
  admin:
    user: admin
    password: admin

logging:
  level:
    com.lenovo.accountservice: debug
    org.apache.kafka: warn

swagger:
  api:
    title: Account Service API
    description: Service for managing accounts
    version: 1.0


application:
  web-security-config:
    custom-unsecured-endpoints: /accounts/**
